trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
pr:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
strategy:
  matrix:
    Linux_Build_and_Test:
      imageName: ubuntu-latest
    MacOS_Build_and_Test:
      imageName: macOS-latest
    Windows_Build_Test_and_Package:
      imageName: windows-latest
pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    verbosityRestore: normal
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    arguments: '--no-restore -c $(buildConfiguration) -v n' # /p:TreatWarningsAsErrors=True
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    arguments: '--no-build -c $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include="[Steeltoe.*]*" /p:Exclude="[*.Test*]*"'
    publishTestResults: true
